import html

from app.models import ScanReport

PERSONA_LABEL = {
    "color_blind": "Color-blind user",
    "low_vision": "Low-vision user",
    "motor_impaired": "Motor-impaired user",
    "screen_reader": "Screen-reader user",
}


def render_report_html(report: ScanReport) -> str:
    findings_html = ""
    for journey in report.journeys:
        findings_html += f'<h2>{html.escape(journey.name)}</h2>'
        if not journey.findings:
            findings_html += "<p class='muted'>No barriers found in this journey.</p>"
        for f in journey.findings:
            tags_html = "".join(
                f"<span class='tag'>{html.escape(t.law)}: {html.escape(t.reference)}</span>"
                for t in f.compliance_tags
            )
            code_html = ""
            if f.code_after:
                code_html = f"<pre><code>{html.escape(f.code_after)}</code></pre>"
            findings_html += f"""
            <div class="finding sev-{f.severity.value}">
              <div class="finding-head">
                <strong>{html.escape(f.title)}</strong>
                <span class="badge">{f.severity.value.upper()}</span>
                <span class="badge persona">{PERSONA_LABEL.get(f.persona.value, f.persona.value)}</span>
                <span class="badge">{'AUTO-FIXABLE' if f.auto_fixable else 'NEEDS MANUAL REVIEW'}</span>
              </div>
              <p>{html.escape(f.user_impact)}</p>
              <p class="fix"><strong>Suggested fix:</strong> {html.escape(f.suggested_fix)}</p>
              {code_html}
              <p class="tags">{tags_html}</p>
            </div>
            """

    high_risk = "".join(f"<li>{html.escape(j)}</li>" for j in report.summary.high_risk_journeys)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>AccessLens Report - {html.escape(report.url)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Arial, sans-serif; color: #0f172a; margin: 40px; }}
  h1 {{ font-size: 1.6rem; margin-bottom: 4px; }}
  .muted {{ color: #64748b; }}
  .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 24px 0; }}
  .stat {{ border: 1px solid #cbd5e1; border-radius: 10px; padding: 12px; text-align: center; }}
  .stat strong {{ display: block; font-size: 1.6rem; }}
  .finding {{ border: 1px solid #cbd5e1; border-left-width: 5px; border-radius: 8px; padding: 12px 16px; margin: 10px 0; }}
  .finding.sev-critical, .finding.sev-serious {{ border-left-color: #dc2626; }}
  .finding.sev-moderate {{ border-left-color: #d97706; }}
  .finding.sev-minor {{ border-left-color: #64748b; }}
  .finding-head {{ display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }}
  .badge {{ font-size: 0.7rem; font-weight: 700; padding: 2px 8px; border-radius: 999px; background: #e2e8f0; }}
  .badge.persona {{ background: #dbeafe; }}
  .fix {{ background: #f8fafc; padding: 8px; border-radius: 6px; }}
  pre {{ background: #0f172a; color: #e2e8f0; padding: 10px; border-radius: 6px; overflow-x: auto; }}
  .tags {{ font-size: 0.72rem; color: #475569; }}
  .tag {{ margin-right: 10px; }}
</style>
</head>
<body>
  <h1>AccessLens India Accessibility Report</h1>
  <p class="muted">{html.escape(report.url)} &middot; scanned {html.escape(report.created_at)}</p>

  <div class="summary">
    <div class="stat"><strong>{report.summary.journeys_tested}</strong>Journeys tested</div>
    <div class="stat"><strong>{report.summary.barriers_found}</strong>Barriers found</div>
    <div class="stat"><strong>{report.summary.auto_fixable}</strong>Auto-fixable</div>
    <div class="stat"><strong>{report.summary.needs_manual}</strong>Needs manual testing</div>
  </div>

  <p><strong>IS 17802 readiness:</strong> {report.summary.is17802_readiness_pct}%</p>
  <p><strong>High-risk journeys for RPwD complaints:</strong></p>
  <ul>{high_risk or '<li>None identified</li>'}</ul>

  {findings_html}

  <p class="muted" style="margin-top:32px;">
    This report is generated by automated testing and covers roughly 30-40% of real-world
    accessibility barriers. It is not a substitute for manual testing with real assistive
    technology (NVDA, VoiceOver) and real disabled users.
  </p>
</body>
</html>"""
